### ISSUE TITLE
Indicate installation failure

### ISSUE THREAD

**Issue by ChinaArJun** [heisian/Z370M-ITX-AC-macOS#1]
Indicate installation failure

**Comment by heisian** [comment]
are you having issues with your install?

**Comment by ChinaArJun** [comment]
Yes, but my configuration table is a bit different from yours.
![wechatimg21](https://user-images.githubusercontent.com/15144287/34399139-863216b0-ebbf-11e7-8745-9029f086988a.jpeg)

**Comment by heisian** [comment]
You should not be looking at this repo for configuration.. you are using an MSI motherboard which likely has an entirely different set of conditions to get working with macOS.

**Comment by heisian** [comment]
Your config is going to be more similar to this:
http://hackintosher.com/builds/msi-b250m-bazooka-hackintosh-build-guide/

Although, you will still have to experiment since the chipset is different. But within manufacturers configurations are more consistent.
