### ISSUE TITLE
Question: have you tried upgrading past 10.13.4?

### ISSUE THREAD

**Issue by CoreyCole** [heisian/Z370M-ITX-AC-macOS#4]
I'm only able to get 10.13.6 and I'm wondering if that might be why I can't seem to get ethernet working.

[This](https://www.tonymacx86.com/threads/solved-updated-10-13-4-to-10-13-5-and-intelmausiethernet-v2-4-0-kernel-panic.256882/) is why I'm suspicious of the osx version.

The `IntelMausiEthernet.kext` doesn't seem to be injected or something because when I go to `About This Mac>System Report>Hardware>Ethernet Cards` it is not present there.

I've tried replacing the `IntelMausiEthernet.kext` inside the `Clover>kexts>Other` folder with `AppleIntelE1000e.kext` as suggested in the forum thread linked above, and I get stuck in a boot loop 😕

**Comment by CoreyCole** [comment]
solved by switching which ethernet port I was plugging into... 🎉

**Comment by heisian** [comment]
ha! yeah, it's a bit annoying that only one works. glad it worked out for you

**Comment by heisian** [comment]
another caveat worth mentioning, sleep doesn't seem to work with certain USB devices plugged in.

For example, I have a USB C ethernet adapter with 3 USB 3.0 ports, and when I plug that in to the back of the mobo (with a USB C to USB 3.0 adapter), and chain a keyboard to it, my computer won't wake from sleep.

Plugging in my keyboard directly to the mobo and putting the BIOS legacy usb support to "UEFI setup only" works in the various boot screens and also w/ sleep.

I have an external hard drive I use for Time Machine that seems to not affect sleep.

**Comment by CoreyCole** [comment]
Interesting, I haven't noticed any sleep-wake issues but I will keep that in mind. Thank you!

**Comment by heisian** [comment]
no worries, yeah, it seems to be a rare issue that only affects certain USB devices. glad your rig is workin out!

**Comment by CoreyCole** [comment]
I really love it, couldn't have done it without your work here 😄 

Love the clover theme btw

**Comment by samlader** [comment]
Have either of you looked into upgrading to Mojave? @CoreyCole @heisian

**Comment by CoreyCole** [comment]
Nah I'm happy with it working. I don't even plan on updating my MacBook pro for a long time 😂

**Comment by heisian** [comment]
I will be attempting Mojave soon. will post results when I do.
